- 클래스 = 정보와 처리
- 정보 = 클래스 (static) 인스턴스 (heap memory)
- 처리 = 클래스 메소드, 인스턴스 메소드
- 클래스는 상속을 따로 받지 않아도 기본적으로 오브젝트에 의해 자동으로 상속된다.
- object의 메소드 : equals(동일 비교), getclass(), hashcode, tostring()
- 객체가 new 할 때 생성자(Constructor)가 호출된다.
- 오버로딩 : 같은 이름의 메소드를 여러개 정의하는 것
- 메소드에 final을 붙이면 오버라이딩을 할 수 없다.
![](20250327095039.png)

 <br>

 - 추상 클래스

![](20250327095235.png)

- 포유류와 조류의 공통점은 생물체라는 것이다. (공통점을 모은다 = 추상화)
- 추상클래스 : 추상 메소드가 하나는 필요하다(처리)
    - 추상메소드 : 이런 처리가 필요한데? 라고 말만 함. 이 처리에 대한 구체적인 구현은 다른 클래스에게 시킴. 상대방에게 <font color = red>**강제로 상속받게 만듬.**</font> (내가 가진 정보와 처리를 사용하고 싶으면 네가 이 처리에 대한 구현을 해야돼.) 오버라이딩 규칙이 적용된다. (약간 구현을 하청 주는 느낌...) / 서블릿에서 사용(JSP)
- 공통된 업무는 부모 클래스에 둬야만 함. 하지만 처리는 각자의 자식 클래스에 따로따로 만들어 두는 것이 좋을 것 같은 경우 해당 메소드를 추상메소드로 설정.
- <font color = red>**추상클래스는 NEW할 수 없다.**</font>

<br>

- 인터페이스
  
![](20250327100744.png)

- A : 카카오 / B : 라인
- 카카오와 라인 사이를 연결.
- 인터페이스도 **추상 메소드**이므로 이런 기능 필요할듯? 하고 운만 띄움.
- 해당 **기능을 필요로 하는 두** <font color = red>**클래스가 해당 기능을 직접 구현**</font>한다.
- 그렇게 되면 두 객체가 인터페이스를 통해 서로 연결된다.

<br>

- POJO(Plain Old Java Object) : 상속, 인터페이스 이런거 다 사용하지 않는 순수한 자바 객체만 이용하는 것
- 클래스만 만들면 Spring Framework가 나머지 설계 완료해준다. 

<br>

# 예외처리(Exception Handling)

- 오류 : 문법적인 실수. 컴파일 과정에서 어디서 오류가 난건지 알 수 있음.
- 예외 : 프로그램 실행 중에 발생하는 예외적인 상황. 단순 문법 오류가 아닌 실행 중간에 발생하는 정상적이지 않은 상황.

```java
 public static void main(String[] args) {
        Scanner kb = new Scanner(System.in);
    
        System.out.print("a/b... a? ");
        int n1 = kb.nextInt(); //정수로 입력받음
        
        System.out.print("a/b... b? ");
        int n2 = kb.nextInt();
        
        System.out.printf("%d / %d = %d \n", n1, n2, n1/n2);
        System.out.println("Good bye~~!");
```

```
a/b... a? 8
a/b... b? 0 //오류 발생. 나눗셈에 0을 쓸 수 없음

```
- Ctrl + Shift + T : Type찾기
- Ctrl + Shift + R : 소스 찾기


![](20250327105518.png)
- Arithmetic Exception은 RuntimeException(실행중 예외발생) 이다.
- 

<br>

```java
public static void main(String[] args) {
        Scanner kb = new Scanner(System.in);

        try { //이 블럭에서 문제가 생기면
            System.out.print("a/b... a? ");
            int n1 = kb.nextInt();
            
            System.out.print("a/b... b? ");
            int n2 = kb.nextInt();
        
            System.out.printf("%d / %d = %d \n", n1, n2, n1/n2);
        }
        catch(ArithmeticException e) { //이 예외를 잡겠다.
        e.printStackTrace(); //스택 히스토리를 출력해야 어디를 수정해야할지 알 수 있음.
            System.out.println(e.getMessage());
        }

        System.out.println("Good bye~~!");
    }
```

```
<출력내용>
a/b... a? 10
a/b... b? 0
java.lang.ArithmeticException: / by zero
/ by zero
Good bye~~!
	at ExceptionCase2.main(ExceptionCase2.java:14) //어디에서 오류가 발생한건지 확인 가능
```

<br>

- 예외 오류가 떠지면 자바는 해당 오류 내역을 new해서 메모리에 올림.
- new ArithmeticException(); 를 try 블록에 넣으면 강제로 예외를 발생시킴. 해당 프로그램에 브레이크 걸림.


```java
public static void main(String[] args) {
        Scanner kb = new Scanner(System.in);

        try {
            System.out.print("a/b... a? ");
            int n1 = kb.nextInt();
            
            System.out.print("a/b... b? ");
            int n2 = kb.nextInt();
        
            System.out.printf("%d / %d = %d \n", n1, n2, n1/n2);
        }
        catch(InputMismatchException e) {
            e.getMessage();
        }

        System.out.println("Good bye~~!");
```

- InputMismatchException만 사용하면 ArithmeticException을 잡아낼 수 없어서 예외 발생.
- 두 가지 모두 예외처리 하고 싶다면 두 catch구문을 사용하면 된다.
- or기호 (|)를 사용하여 각각의 catch를 하나로 합쳐서 사용할 수 있다. 
  - catch (ArithmeticException | InputMismatchException e) {
  e.getMessage();}

<br>

- Throwable 클래스 : 터졌다고 알려줌.
<br>

```java
void b() throws Exception {
		
	}
	
	void a() {
		try {
			
		} catch (Exception e) {
			//내가 처리할것...
			throw e; //던지기
		}
	}
```

<br>

- Error클래스 상속
- Exception 클래스 상속 (컴파일시 보임)
- RuntimeException 클래스 상속 = 해당 클래스는 Exception 클래스를 상속한다.
- 에러 클래스 : VirtureMachinError / IOError(인풋, 아웃풋 입출력오류)
- OutOfMemoryError : 프로그램 실행에 필요한 메모리가 부족해서 생기는 예외
- Exception을 여러개 쓰고 싶을때는 범위가 작은 exception을 먼저 사용해야 한다.

<br>

```java
class ReadAgeException extends Exception {
    public ReadAgeException() {
        super("유효하지 않은 나이가 입력되었습니다.");
    }
}
```

- exception을 만들고 싶을때 클래스를 만들어서 Exception을 상속받으면 됨.

<br>

```java
public class JptTestException extends Exception{

	public JptTestException() {
		super("노력부족");
	}
}
```

<br>

```java
package jpt;

import java.util.Scanner;

import exception.JptTestException;

public class jptTest {

	public static void main(String[] args) throws JptTestException {

		Scanner scan = new Scanner(System.in);
		System.out.println("일본어로 자기소개를 해보세요");
		String selfIntroduce = scan.next();
		if (50 > selfIntroduce.length()) {
			throw new JptTestException();
		} else {
			System.out.println("JPT 합격");
		}

	}
}
```
- exception을 직접 생성하여 상속받는 코드

- finally : 마지막 정리를 작성하는 블록. close()를 함께 사용.
  
<br>

![](20250327161053.png)

<br>

![](20250327161627.png)

<br>
